 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/fyusion-pytorch-img:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/fyusion-pytorch-img:$COMMIT_SHA']
 images:
 - 'gcr.io/$PROJECT_ID/fyusion-pytorch-img:$COMMIT_SHA'
