 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/fyusion-pytorch-img:$COMMIT_SHA', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/fyusion-pytorch-img:$COMMIT_SHA']
 images:
 - 'gcr.io/$PROJECT_ID/fyusion-pytorch-img:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/git'
    id: Copy to production branch
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      set -x && \
      # Configure Git to create commits with Cloud Build's service account
      git config --global user.name "sushant8888" && \
      git config --global user.email "sushant3796@gmail.com" && \
      # Switch to the production branch and copy the kubernetes.yaml file from the candidate branch
      git fetch https://github.com/Sushant8888/cloud-build.git env && git checkout -t -b env && \
      git checkout $COMMIT_SHA testing.py && \
      # Commit the kubernetes.yaml file with a descriptive commit message
      git commit -m "yaml from commit $COMMIT_SHA
      $(git log --format=%B -n 1 $COMMIT_SHA)" && \
      # Push the changes back to Cloud Source Repository
      git push https://github.com/Sushant8888/cloud-build.git env
